# Generated by Django 5.2.15 on 2026-07-19 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('purpose', models.TextField(blank=True, default='', verbose_name='Nima uchun ishlatiladi (izoh)')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Tartib (kichik raqam — avval sinaladi)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('provider', models.CharField(blank=True, choices=[('openrouter', 'OpenRouter'), ('groq', 'Groq'), ('gemini', 'Google Gemini'), ('mistral', 'Mistral'), ('cerebras', 'Cerebras'), ('google_openai', 'Google AI Studio (OpenAI-mos)'), ('dashscope', 'Alibaba Cloud (DashScope)'), ('cohere', 'Cohere'), ('github_models', 'GitHub Models'), ('custom', 'Boshqa (maxsus Base URL)'), ('', 'Aniqlanmagan')], default='', max_length=20)),
                ('base_url', models.CharField(blank=True, default='', max_length=255, verbose_name="Maxsus Base URL (OpenAI-mos /chat/completions; bo'sh qoldirsa provayder kalitdan avtomatik aniqlanadi)")),
                ('model_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Model')),
                ('keys', models.JSONField(blank=True, default=list, verbose_name='Kalitlar (har biri mustaqil holat bilan)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tekin API kalit',
                'verbose_name_plural': 'Tekin API kalitlari',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
