# Generated by Django 5.2.15 on 2026-07-20 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('rate_limited_requests', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API analytics',
                'verbose_name_plural': 'API analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('valid', 'Ishlayapti'), ('invalid', 'Yaroqsiz/xato'), ('rate_limited', 'Limit tugagan'), ('unknown', 'Tekshirilmagan')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'API foydalanish logi',
                'verbose_name_plural': 'API foydalanish loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='freeapikey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi'),
        ),
        migrations.AddIndex(
            model_name='freeapikey',
            index=models.Index(fields=['priority', 'is_active'], name='api_freeapi_priorit_bdd3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='freeapikey',
            index=models.Index(fields=['provider'], name='api_freeapi_provide_0ca06f_idx'),
        ),
        migrations.AddField(
            model_name='apianalytics',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.freeapikey'),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api.freeapikey'),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apianalytics',
            index=models.Index(fields=['date', 'api_key'], name='api_apianal_date_8ce069_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apianalytics',
            unique_together={('date', 'api_key')},
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['api_key', '-created_at'], name='api_apiusag_api_key_dbba5e_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['status', '-created_at'], name='api_apiusag_status_6af8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['user', '-created_at'], name='api_apiusag_user_id_e99861_idx'),
        ),
    ]
