# Generated by Django 5.2.15 on 2026-07-20 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Provider kodi')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('adapter_class_path', models.CharField(blank=True, default='', max_length=255, verbose_name="Adapter klass yo'li (masalan: apps.ai_providers.adapters.openai.OpenAIAdapter)")),
                ('is_free_tier_available', models.BooleanField(default=False, verbose_name='Tekin tier bormi?')),
                ('default_base_url', models.URLField(blank=True, default='', verbose_name='Standart base URL')),
                ('logo', models.CharField(blank=True, default='', max_length=255, verbose_name='Logo (emoji/CSS)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI provayder',
                'verbose_name_plural': 'AI provayderlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label (masalan: Mening OpenAI kalitim)')),
                ('api_key', models.TextField(verbose_name='API kalit')),
                ('base_url_override', models.URLField(blank=True, default='', verbose_name='Base URL (ixtiyoriy)')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model nomi')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha sozlamalar (temperature va h.k.)")),
                ('is_valid', models.BooleanField(default=True, verbose_name='Kalit ishlaydimi?')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi tekshirilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_providers.aiprovider', verbose_name='Provayder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credentials', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI provayder kaliti',
                'verbose_name_plural': 'AI provayder kalitlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
