# Generated by Django 5.2.15 on 2026-07-20 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_providers', '0001_initial'),
        ('social', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default="Siz foydalanuvchilarga yordam beruvchi AI yordamchisiz. Savollarga aniq, foydali va do'stona javob bering.", verbose_name='Tizim prompti')),
                ('tone', models.CharField(default="do'stona", max_length=50, verbose_name='Ohang')),
                ('language_mode', models.CharField(choices=[('auto', 'Avtomatik'), ('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz')], default='auto', max_length=10, verbose_name='Til rejimi')),
                ('max_response_length', models.PositiveIntegerField(default=1000, verbose_name='Maksimal javob uzunligi (belgi)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Agent faolmi?')),
                ('fallback_to_human', models.BooleanField(default=True, verbose_name='AI ishlamasa odamga otkazish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('ai_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_providers.aiprovidercredential', verbose_name='AI kaliti')),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='social.socialaccount', verbose_name='Ijtimoiy akkaunt')),
            ],
            options={
                'verbose_name': 'Agent sozlamasi',
                'verbose_name_plural': 'Agent sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=255, verbose_name='Tashqi foydalanuvchi ID')),
                ('external_user_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Tashqi foydalanuvchi nomi')),
                ('incoming_message', models.TextField(verbose_name='Kiruvchi xabar')),
                ('ai_response', models.TextField(blank=True, default='', verbose_name='AI javobi')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan tokenlar')),
                ('response_time_ms', models.PositiveIntegerField(default=0, verbose_name='Javob vaqti (ms)')),
                ('status', models.CharField(choices=[('sent', 'Yuborildi'), ('failed', 'Xato'), ('escalated', 'Odamga otkazildi')], default='sent', max_length=20, verbose_name='Holati')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Xato xabari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='social.socialaccount', verbose_name='Ijtimoiy akkaunt')),
            ],
            options={
                'verbose_name': 'Muloqot logi',
                'verbose_name_plural': 'Muloqot loglari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['social_account', '-created_at'], name='agents_conv_social__ca88e3_idx'), models.Index(fields=['external_user_id'], name='agents_conv_externa_537f30_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('messages_count', models.PositiveIntegerField(default=0, verbose_name='Xabarlar soni')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokenlar')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='social.socialaccount', verbose_name='Ijtimoiy akkaunt')),
            ],
            options={
                'verbose_name': 'Foydalanish statistikasi',
                'verbose_name_plural': 'Foydalanish statistikasi',
                'ordering': ['-date'],
                'unique_together': {('social_account', 'date')},
            },
        ),
    ]
