# Generated by Django 5.2.15 on 2026-07-20 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Platforma kodi')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('logo', models.CharField(blank=True, default='', max_length=255, verbose_name='Logo ikonka (CSS class yoki emoji)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150, verbose_name="Ko'rinadigan nom")),
                ('external_id', models.CharField(max_length=255, verbose_name='Tashqi ID (bot_id, page_id va h.k.)')),
                ('access_token', models.TextField(verbose_name='Access token / Bot token')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255, verbose_name="Webhook maxfiy so'zi")),
                ('status', models.CharField(choices=[('active', 'Faol'), ('paused', 'Pauza'), ('error', 'Xato')], default='active', max_length=20, verbose_name='Holati')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Ulanganki?')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Ulangan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.socialplatform', verbose_name='Platforma')),
            ],
            options={
                'verbose_name': 'Ijtimoiy akkaunt',
                'verbose_name_plural': 'Ijtimoiy akkauntlar',
                'ordering': ['-connected_at'],
                'unique_together': {('user', 'platform', 'external_id')},
            },
        ),
    ]
