# Generated by Django 5.2.15 on 2026-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='account_type',
            field=models.CharField(choices=[('bot', 'Bot'), ('user', 'User account')], default='bot', max_length=10, verbose_name='Akkaunt turi'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='api_hash',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='API Hash (my.telegram.org)'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='api_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='API ID (my.telegram.org)'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='auth_code_hash',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Auth code hash (ichki)'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon raqam'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='session_data',
            field=models.TextField(blank=True, default='', verbose_name='Telethon session (base64)'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(blank=True, default='', verbose_name='Bot token'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tashqi ID'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('paused', 'Pauza'), ('error', 'Xato'), ('pending', 'Kutilmoqda')], default='active', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='socialplatform',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Logo ikonka'),
        ),
    ]
